"""empty message

Revision ID: 0ad2de646444
Revises: 
Create Date: 2021-09-26 13:39:54.161327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad2de646444'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copy_txns', 'cancelTransactionHash_y')
    op.drop_column('copy_txns', 'bidSignature')
    op.drop_column('copy_txns', 'transactionId')
    op.drop_column('copy_txns', 'sendingChainId')
    op.drop_column('copy_txns', 'sendingChainFallback')
    op.drop_column('copy_txns', 'fulfillCaller_x')
    op.drop_column('copy_txns', 'receivingAddress')
    op.drop_column('copy_txns', 'cancelCaller_y')
    op.drop_column('copy_txns', 'prepareTransactionHash_y')
    op.drop_column('copy_txns', 'chainId_x')
    op.drop_column('copy_txns', 'receivingChainId')
    op.drop_column('copy_txns', 'callTo')
    op.drop_column('copy_txns', 'router')
    op.drop_column('copy_txns', 'callDataHash')
    op.drop_column('copy_txns', 'prepareCaller_y')
    op.drop_column('copy_txns', 'fulfillCaller_y')
    op.drop_column('copy_txns', 'prepareCaller_x')
    op.drop_column('copy_txns', 'fulfillTransactionHash_y')
    op.drop_column('copy_txns', 'receivingChainTxManagerAddress')
    op.drop_column('copy_txns', 'cancelCaller_x')
    op.drop_column('copy_txns', 'prepareTransactionHash_x')
    op.drop_column('copy_txns', 'cancelTransactionHash_x')
    op.drop_column('copy_txns', 'fulfillTransactionHash_x')
    op.drop_column('copy_txns', 'chainId_y')
    op.drop_column('txns', 'cancelTransactionHash_y')
    op.drop_column('txns', 'bidSignature')
    op.drop_column('txns', 'transactionId')
    op.drop_column('txns', 'sendingChainId')
    op.drop_column('txns', 'sendingChainFallback')
    op.drop_column('txns', 'fulfillCaller_x')
    op.drop_column('txns', 'receivingAddress')
    op.drop_column('txns', 'cancelCaller_y')
    op.drop_column('txns', 'prepareTransactionHash_y')
    op.drop_column('txns', 'chainId_x')
    op.drop_column('txns', 'receivingChainId')
    op.drop_column('txns', 'callTo')
    op.drop_column('txns', 'router')
    op.drop_column('txns', 'callDataHash')
    op.drop_column('txns', 'prepareCaller_y')
    op.drop_column('txns', 'fulfillCaller_y')
    op.drop_column('txns', 'prepareCaller_x')
    op.drop_column('txns', 'fulfillTransactionHash_y')
    op.drop_column('txns', 'receivingChainTxManagerAddress')
    op.drop_column('txns', 'cancelCaller_x')
    op.drop_column('txns', 'prepareTransactionHash_x')
    op.drop_column('txns', 'cancelTransactionHash_x')
    op.drop_column('txns', 'fulfillTransactionHash_x')
    op.drop_column('txns', 'chainId_y')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('txns', sa.Column('chainId_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('fulfillTransactionHash_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('cancelTransactionHash_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('prepareTransactionHash_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('cancelCaller_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('receivingChainTxManagerAddress', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('fulfillTransactionHash_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('prepareCaller_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('fulfillCaller_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('prepareCaller_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('callDataHash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('router', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('callTo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('receivingChainId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('chainId_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('prepareTransactionHash_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('cancelCaller_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('receivingAddress', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('fulfillCaller_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('sendingChainFallback', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('sendingChainId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('transactionId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('bidSignature', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('txns', sa.Column('cancelTransactionHash_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('chainId_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('fulfillTransactionHash_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('cancelTransactionHash_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('prepareTransactionHash_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('cancelCaller_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('receivingChainTxManagerAddress', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('fulfillTransactionHash_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('prepareCaller_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('fulfillCaller_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('prepareCaller_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('callDataHash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('router', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('callTo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('receivingChainId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('chainId_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('prepareTransactionHash_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('cancelCaller_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('receivingAddress', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('fulfillCaller_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('sendingChainFallback', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('sendingChainId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('transactionId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('bidSignature', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('copy_txns', sa.Column('cancelTransactionHash_y', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
