"""empty message

Revision ID: d4c415128480
Revises: 
Create Date: 2021-10-04 22:34:19.570183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c415128480'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridges_tvl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('chain', sa.String(), nullable=True),
    sa.Column('bridge', sa.String(), nullable=True),
    sa.Column('tvl', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('asset_movement', 'id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.drop_index('ix_asset_movement_id', table_name='asset_movement')
    op.alter_column('date_volume', 'id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.drop_index('ix_date_volume_id', table_name='date_volume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_date_volume_id', 'date_volume', ['id'], unique=False)
    op.alter_column('date_volume', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.create_index('ix_asset_movement_id', 'asset_movement', ['id'], unique=False)
    op.alter_column('asset_movement', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_table('bridges_tvl')
    # ### end Alembic commands ###
