"""empty message

Revision ID: e7a48deffe91
Revises: 0ad2de646444
Create Date: 2021-09-26 22:26:25.529806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7a48deffe91'
down_revision = '0ad2de646444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_movement', sa.String(), nullable=True),
    sa.Column('txns', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('time_taken', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date_volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('txns', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('misc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('copy_txns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copy_txns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount_x', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expiry_x', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fulfillTimestamp_x', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subgraphId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preparedBlockNumber_x', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preparedTimestamp_x', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('receivingAssetId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sendingAssetId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_x', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chain_x', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('txn_type_x', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_movement', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('decimals_x', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dollar_amount_x', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('time_prepared_x', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time_fulfilled_x', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('amount_y', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expiry_y', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fulfillTimestamp_y', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preparedBlockNumber_y', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preparedTimestamp_y', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_y', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chain_y', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('txn_type_y', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('decimals_y', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dollar_amount_y', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('time_prepared_y', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time_fulfilled_y', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time_taken', postgresql.INTERVAL(), autoincrement=False, nullable=True),
    sa.Column('time_taken_seconds', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='copy_txns_pkey')
    )
    op.drop_table('misc')
    op.drop_table('date_volume')
    op.drop_table('asset_movement')
    # ### end Alembic commands ###
